version: "3.8"

services:
  web:
    build:
      # Переходим на уровень выше, чтобы Docker "видел" все файлы (pyproject.toml, poetry.lock)
      # Если у вас структура другая – корректируйте пути.
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      # Здесь можно пробросить переменные окружения для приложения
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    depends_on:
      - db

  # Контейнер с PostgreSQL (или другой СУБД)
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: